# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/137/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/137/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tarik/Mobar-Coder/Secret-Bundestag-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tarik/Mobar-Coder/Secret-Bundestag-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/137/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/137/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tarik/Mobar-Coder/Secret-Bundestag-Server/CMakeFiles /home/tarik/Mobar-Coder/Secret-Bundestag-Server/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tarik/Mobar-Coder/Secret-Bundestag-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SecretBundestagServer

# Build rule for target.
SecretBundestagServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SecretBundestagServer
.PHONY : SecretBundestagServer

# fast build rule for target.
SecretBundestagServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/build
.PHONY : SecretBundestagServer/fast

#=============================================================================
# Target rules for targets named WebsocketCpp

# Build rule for target.
WebsocketCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebsocketCpp
.PHONY : WebsocketCpp

# fast build rule for target.
WebsocketCpp/fast:
	$(MAKE) $(MAKESILENT) -f lib/WebsocketCpp/CMakeFiles/WebsocketCpp.dir/build.make lib/WebsocketCpp/CMakeFiles/WebsocketCpp.dir/build
.PHONY : WebsocketCpp/fast

#=============================================================================
# Target rules for targets named WebSocketCppClientExample

# Build rule for target.
WebSocketCppClientExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebSocketCppClientExample
.PHONY : WebSocketCppClientExample

# fast build rule for target.
WebSocketCppClientExample/fast:
	$(MAKE) $(MAKESILENT) -f lib/WebsocketCpp/examples/CMakeFiles/WebSocketCppClientExample.dir/build.make lib/WebsocketCpp/examples/CMakeFiles/WebSocketCppClientExample.dir/build
.PHONY : WebSocketCppClientExample/fast

#=============================================================================
# Target rules for targets named WebsocketCppServerExample

# Build rule for target.
WebsocketCppServerExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebsocketCppServerExample
.PHONY : WebsocketCppServerExample

# fast build rule for target.
WebsocketCppServerExample/fast:
	$(MAKE) $(MAKESILENT) -f lib/WebsocketCpp/examples/CMakeFiles/WebsocketCppServerExample.dir/build.make lib/WebsocketCpp/examples/CMakeFiles/WebsocketCppServerExample.dir/build
.PHONY : WebsocketCppServerExample/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousSubmit.dir/build.make lib/json/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousCoverage.dir/build.make lib/json/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousBuild.dir/build.make lib/json/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousUpdate.dir/build.make lib/json/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyTest.dir/build.make lib/json/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyUpdate.dir/build.make lib/json/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyBuild.dir/build.make lib/json/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/Continuous.dir/build.make lib/json/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousTest.dir/build.make lib/json/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousMemCheck.dir/build.make lib/json/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/Nightly.dir/build.make lib/json/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyStart.dir/build.make lib/json/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyMemoryCheck.dir/build.make lib/json/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyMemCheck.dir/build.make lib/json/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalStart.dir/build.make lib/json/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousConfigure.dir/build.make lib/json/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyCoverage.dir/build.make lib/json/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalUpdate.dir/build.make lib/json/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalConfigure.dir/build.make lib/json/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalCoverage.dir/build.make lib/json/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalBuild.dir/build.make lib/json/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlyConfigure.dir/build.make lib/json/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalTest.dir/build.make lib/json/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalMemCheck.dir/build.make lib/json/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/Experimental.dir/build.make lib/json/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/NightlySubmit.dir/build.make lib/json/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ExperimentalSubmit.dir/build.make lib/json/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f lib/json/CMakeFiles/ContinuousStart.dir/build.make lib/json/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

src/comm/ConnectionHandler.o: src/comm/ConnectionHandler.cpp.o

.PHONY : src/comm/ConnectionHandler.o

# target to build an object file
src/comm/ConnectionHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/ConnectionHandler.cpp.o
.PHONY : src/comm/ConnectionHandler.cpp.o

src/comm/ConnectionHandler.i: src/comm/ConnectionHandler.cpp.i

.PHONY : src/comm/ConnectionHandler.i

# target to preprocess a source file
src/comm/ConnectionHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/ConnectionHandler.cpp.i
.PHONY : src/comm/ConnectionHandler.cpp.i

src/comm/ConnectionHandler.s: src/comm/ConnectionHandler.cpp.s

.PHONY : src/comm/ConnectionHandler.s

# target to generate assembly for a file
src/comm/ConnectionHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/ConnectionHandler.cpp.s
.PHONY : src/comm/ConnectionHandler.cpp.s

src/comm/Lobby.o: src/comm/Lobby.cpp.o

.PHONY : src/comm/Lobby.o

# target to build an object file
src/comm/Lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/Lobby.cpp.o
.PHONY : src/comm/Lobby.cpp.o

src/comm/Lobby.i: src/comm/Lobby.cpp.i

.PHONY : src/comm/Lobby.i

# target to preprocess a source file
src/comm/Lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/Lobby.cpp.i
.PHONY : src/comm/Lobby.cpp.i

src/comm/Lobby.s: src/comm/Lobby.cpp.s

.PHONY : src/comm/Lobby.s

# target to generate assembly for a file
src/comm/Lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/Lobby.cpp.s
.PHONY : src/comm/Lobby.cpp.s

src/comm/LobbyHandler.o: src/comm/LobbyHandler.cpp.o

.PHONY : src/comm/LobbyHandler.o

# target to build an object file
src/comm/LobbyHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/LobbyHandler.cpp.o
.PHONY : src/comm/LobbyHandler.cpp.o

src/comm/LobbyHandler.i: src/comm/LobbyHandler.cpp.i

.PHONY : src/comm/LobbyHandler.i

# target to preprocess a source file
src/comm/LobbyHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/LobbyHandler.cpp.i
.PHONY : src/comm/LobbyHandler.cpp.i

src/comm/LobbyHandler.s: src/comm/LobbyHandler.cpp.s

.PHONY : src/comm/LobbyHandler.s

# target to generate assembly for a file
src/comm/LobbyHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/comm/LobbyHandler.cpp.s
.PHONY : src/comm/LobbyHandler.cpp.s

src/gamelogic/gamecontroller/Controller.o: src/gamelogic/gamecontroller/Controller.cpp.o

.PHONY : src/gamelogic/gamecontroller/Controller.o

# target to build an object file
src/gamelogic/gamecontroller/Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamecontroller/Controller.cpp.o
.PHONY : src/gamelogic/gamecontroller/Controller.cpp.o

src/gamelogic/gamecontroller/Controller.i: src/gamelogic/gamecontroller/Controller.cpp.i

.PHONY : src/gamelogic/gamecontroller/Controller.i

# target to preprocess a source file
src/gamelogic/gamecontroller/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamecontroller/Controller.cpp.i
.PHONY : src/gamelogic/gamecontroller/Controller.cpp.i

src/gamelogic/gamecontroller/Controller.s: src/gamelogic/gamecontroller/Controller.cpp.s

.PHONY : src/gamelogic/gamecontroller/Controller.s

# target to generate assembly for a file
src/gamelogic/gamecontroller/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamecontroller/Controller.cpp.s
.PHONY : src/gamelogic/gamecontroller/Controller.cpp.s

src/gamelogic/gamemodel/Board.o: src/gamelogic/gamemodel/Board.cpp.o

.PHONY : src/gamelogic/gamemodel/Board.o

# target to build an object file
src/gamelogic/gamemodel/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Board.cpp.o
.PHONY : src/gamelogic/gamemodel/Board.cpp.o

src/gamelogic/gamemodel/Board.i: src/gamelogic/gamemodel/Board.cpp.i

.PHONY : src/gamelogic/gamemodel/Board.i

# target to preprocess a source file
src/gamelogic/gamemodel/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Board.cpp.i
.PHONY : src/gamelogic/gamemodel/Board.cpp.i

src/gamelogic/gamemodel/Board.s: src/gamelogic/gamemodel/Board.cpp.s

.PHONY : src/gamelogic/gamemodel/Board.s

# target to generate assembly for a file
src/gamelogic/gamemodel/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Board.cpp.s
.PHONY : src/gamelogic/gamemodel/Board.cpp.s

src/gamelogic/gamemodel/CardRange.o: src/gamelogic/gamemodel/CardRange.cpp.o

.PHONY : src/gamelogic/gamemodel/CardRange.o

# target to build an object file
src/gamelogic/gamemodel/CardRange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/CardRange.cpp.o
.PHONY : src/gamelogic/gamemodel/CardRange.cpp.o

src/gamelogic/gamemodel/CardRange.i: src/gamelogic/gamemodel/CardRange.cpp.i

.PHONY : src/gamelogic/gamemodel/CardRange.i

# target to preprocess a source file
src/gamelogic/gamemodel/CardRange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/CardRange.cpp.i
.PHONY : src/gamelogic/gamemodel/CardRange.cpp.i

src/gamelogic/gamemodel/CardRange.s: src/gamelogic/gamemodel/CardRange.cpp.s

.PHONY : src/gamelogic/gamemodel/CardRange.s

# target to generate assembly for a file
src/gamelogic/gamemodel/CardRange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/CardRange.cpp.s
.PHONY : src/gamelogic/gamemodel/CardRange.cpp.s

src/gamelogic/gamemodel/Environment.o: src/gamelogic/gamemodel/Environment.cpp.o

.PHONY : src/gamelogic/gamemodel/Environment.o

# target to build an object file
src/gamelogic/gamemodel/Environment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Environment.cpp.o
.PHONY : src/gamelogic/gamemodel/Environment.cpp.o

src/gamelogic/gamemodel/Environment.i: src/gamelogic/gamemodel/Environment.cpp.i

.PHONY : src/gamelogic/gamemodel/Environment.i

# target to preprocess a source file
src/gamelogic/gamemodel/Environment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Environment.cpp.i
.PHONY : src/gamelogic/gamemodel/Environment.cpp.i

src/gamelogic/gamemodel/Environment.s: src/gamelogic/gamemodel/Environment.cpp.s

.PHONY : src/gamelogic/gamemodel/Environment.s

# target to generate assembly for a file
src/gamelogic/gamemodel/Environment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Environment.cpp.s
.PHONY : src/gamelogic/gamemodel/Environment.cpp.s

src/gamelogic/gamemodel/EventTrigger.o: src/gamelogic/gamemodel/EventTrigger.cpp.o

.PHONY : src/gamelogic/gamemodel/EventTrigger.o

# target to build an object file
src/gamelogic/gamemodel/EventTrigger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/EventTrigger.cpp.o
.PHONY : src/gamelogic/gamemodel/EventTrigger.cpp.o

src/gamelogic/gamemodel/EventTrigger.i: src/gamelogic/gamemodel/EventTrigger.cpp.i

.PHONY : src/gamelogic/gamemodel/EventTrigger.i

# target to preprocess a source file
src/gamelogic/gamemodel/EventTrigger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/EventTrigger.cpp.i
.PHONY : src/gamelogic/gamemodel/EventTrigger.cpp.i

src/gamelogic/gamemodel/EventTrigger.s: src/gamelogic/gamemodel/EventTrigger.cpp.s

.PHONY : src/gamelogic/gamemodel/EventTrigger.s

# target to generate assembly for a file
src/gamelogic/gamemodel/EventTrigger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/EventTrigger.cpp.s
.PHONY : src/gamelogic/gamemodel/EventTrigger.cpp.s

src/gamelogic/gamemodel/GameStateRepresentation.o: src/gamelogic/gamemodel/GameStateRepresentation.cpp.o

.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.o

# target to build an object file
src/gamelogic/gamemodel/GameStateRepresentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/GameStateRepresentation.cpp.o
.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.cpp.o

src/gamelogic/gamemodel/GameStateRepresentation.i: src/gamelogic/gamemodel/GameStateRepresentation.cpp.i

.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.i

# target to preprocess a source file
src/gamelogic/gamemodel/GameStateRepresentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/GameStateRepresentation.cpp.i
.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.cpp.i

src/gamelogic/gamemodel/GameStateRepresentation.s: src/gamelogic/gamemodel/GameStateRepresentation.cpp.s

.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.s

# target to generate assembly for a file
src/gamelogic/gamemodel/GameStateRepresentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/GameStateRepresentation.cpp.s
.PHONY : src/gamelogic/gamemodel/GameStateRepresentation.cpp.s

src/gamelogic/gamemodel/Player.o: src/gamelogic/gamemodel/Player.cpp.o

.PHONY : src/gamelogic/gamemodel/Player.o

# target to build an object file
src/gamelogic/gamemodel/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Player.cpp.o
.PHONY : src/gamelogic/gamemodel/Player.cpp.o

src/gamelogic/gamemodel/Player.i: src/gamelogic/gamemodel/Player.cpp.i

.PHONY : src/gamelogic/gamemodel/Player.i

# target to preprocess a source file
src/gamelogic/gamemodel/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Player.cpp.i
.PHONY : src/gamelogic/gamemodel/Player.cpp.i

src/gamelogic/gamemodel/Player.s: src/gamelogic/gamemodel/Player.cpp.s

.PHONY : src/gamelogic/gamemodel/Player.s

# target to generate assembly for a file
src/gamelogic/gamemodel/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/Player.cpp.s
.PHONY : src/gamelogic/gamemodel/Player.cpp.s

src/gamelogic/gamemodel/RuleSet.o: src/gamelogic/gamemodel/RuleSet.cpp.o

.PHONY : src/gamelogic/gamemodel/RuleSet.o

# target to build an object file
src/gamelogic/gamemodel/RuleSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/RuleSet.cpp.o
.PHONY : src/gamelogic/gamemodel/RuleSet.cpp.o

src/gamelogic/gamemodel/RuleSet.i: src/gamelogic/gamemodel/RuleSet.cpp.i

.PHONY : src/gamelogic/gamemodel/RuleSet.i

# target to preprocess a source file
src/gamelogic/gamemodel/RuleSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/RuleSet.cpp.i
.PHONY : src/gamelogic/gamemodel/RuleSet.cpp.i

src/gamelogic/gamemodel/RuleSet.s: src/gamelogic/gamemodel/RuleSet.cpp.s

.PHONY : src/gamelogic/gamemodel/RuleSet.s

# target to generate assembly for a file
src/gamelogic/gamemodel/RuleSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/RuleSet.cpp.s
.PHONY : src/gamelogic/gamemodel/RuleSet.cpp.s

src/gamelogic/gamemodel/SingleCardEventTrigger.o: src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.o

.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.o

# target to build an object file
src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.o
.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.o

src/gamelogic/gamemodel/SingleCardEventTrigger.i: src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.i

.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.i

# target to preprocess a source file
src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.i
.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.i

src/gamelogic/gamemodel/SingleCardEventTrigger.s: src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.s

.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.s

# target to generate assembly for a file
src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.s
.PHONY : src/gamelogic/gamemodel/SingleCardEventTrigger.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/messages/Accept.o: src/messages/Accept.cpp.o

.PHONY : src/messages/Accept.o

# target to build an object file
src/messages/Accept.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Accept.cpp.o
.PHONY : src/messages/Accept.cpp.o

src/messages/Accept.i: src/messages/Accept.cpp.i

.PHONY : src/messages/Accept.i

# target to preprocess a source file
src/messages/Accept.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Accept.cpp.i
.PHONY : src/messages/Accept.cpp.i

src/messages/Accept.s: src/messages/Accept.cpp.s

.PHONY : src/messages/Accept.s

# target to generate assembly for a file
src/messages/Accept.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Accept.cpp.s
.PHONY : src/messages/Accept.cpp.s

src/messages/Error.o: src/messages/Error.cpp.o

.PHONY : src/messages/Error.o

# target to build an object file
src/messages/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Error.cpp.o
.PHONY : src/messages/Error.cpp.o

src/messages/Error.i: src/messages/Error.cpp.i

.PHONY : src/messages/Error.i

# target to preprocess a source file
src/messages/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Error.cpp.i
.PHONY : src/messages/Error.cpp.i

src/messages/Error.s: src/messages/Error.cpp.s

.PHONY : src/messages/Error.s

# target to generate assembly for a file
src/messages/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Error.cpp.s
.PHONY : src/messages/Error.cpp.s

src/messages/GameStart.o: src/messages/GameStart.cpp.o

.PHONY : src/messages/GameStart.o

# target to build an object file
src/messages/GameStart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/GameStart.cpp.o
.PHONY : src/messages/GameStart.cpp.o

src/messages/GameStart.i: src/messages/GameStart.cpp.i

.PHONY : src/messages/GameStart.i

# target to preprocess a source file
src/messages/GameStart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/GameStart.cpp.i
.PHONY : src/messages/GameStart.cpp.i

src/messages/GameStart.s: src/messages/GameStart.cpp.s

.PHONY : src/messages/GameStart.s

# target to generate assembly for a file
src/messages/GameStart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/GameStart.cpp.s
.PHONY : src/messages/GameStart.cpp.s

src/messages/JoinRequest.o: src/messages/JoinRequest.cpp.o

.PHONY : src/messages/JoinRequest.o

# target to build an object file
src/messages/JoinRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/JoinRequest.cpp.o
.PHONY : src/messages/JoinRequest.cpp.o

src/messages/JoinRequest.i: src/messages/JoinRequest.cpp.i

.PHONY : src/messages/JoinRequest.i

# target to preprocess a source file
src/messages/JoinRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/JoinRequest.cpp.i
.PHONY : src/messages/JoinRequest.cpp.i

src/messages/JoinRequest.s: src/messages/JoinRequest.cpp.s

.PHONY : src/messages/JoinRequest.s

# target to generate assembly for a file
src/messages/JoinRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/JoinRequest.cpp.s
.PHONY : src/messages/JoinRequest.cpp.s

src/messages/Message.o: src/messages/Message.cpp.o

.PHONY : src/messages/Message.o

# target to build an object file
src/messages/Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Message.cpp.o
.PHONY : src/messages/Message.cpp.o

src/messages/Message.i: src/messages/Message.cpp.i

.PHONY : src/messages/Message.i

# target to preprocess a source file
src/messages/Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Message.cpp.i
.PHONY : src/messages/Message.cpp.i

src/messages/Message.s: src/messages/Message.cpp.s

.PHONY : src/messages/Message.s

# target to generate assembly for a file
src/messages/Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Message.cpp.s
.PHONY : src/messages/Message.cpp.s

src/messages/Player.o: src/messages/Player.cpp.o

.PHONY : src/messages/Player.o

# target to build an object file
src/messages/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Player.cpp.o
.PHONY : src/messages/Player.cpp.o

src/messages/Player.i: src/messages/Player.cpp.i

.PHONY : src/messages/Player.i

# target to preprocess a source file
src/messages/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Player.cpp.i
.PHONY : src/messages/Player.cpp.i

src/messages/Player.s: src/messages/Player.cpp.s

.PHONY : src/messages/Player.s

# target to generate assembly for a file
src/messages/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/Player.cpp.s
.PHONY : src/messages/Player.cpp.s

src/messages/StartRequest.o: src/messages/StartRequest.cpp.o

.PHONY : src/messages/StartRequest.o

# target to build an object file
src/messages/StartRequest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/StartRequest.cpp.o
.PHONY : src/messages/StartRequest.cpp.o

src/messages/StartRequest.i: src/messages/StartRequest.cpp.i

.PHONY : src/messages/StartRequest.i

# target to preprocess a source file
src/messages/StartRequest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/StartRequest.cpp.i
.PHONY : src/messages/StartRequest.cpp.i

src/messages/StartRequest.s: src/messages/StartRequest.cpp.s

.PHONY : src/messages/StartRequest.s

# target to generate assembly for a file
src/messages/StartRequest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/messages/StartRequest.cpp.s
.PHONY : src/messages/StartRequest.cpp.s

src/util/ArgumentParser.o: src/util/ArgumentParser.cpp.o

.PHONY : src/util/ArgumentParser.o

# target to build an object file
src/util/ArgumentParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/ArgumentParser.cpp.o
.PHONY : src/util/ArgumentParser.cpp.o

src/util/ArgumentParser.i: src/util/ArgumentParser.cpp.i

.PHONY : src/util/ArgumentParser.i

# target to preprocess a source file
src/util/ArgumentParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/ArgumentParser.cpp.i
.PHONY : src/util/ArgumentParser.cpp.i

src/util/ArgumentParser.s: src/util/ArgumentParser.cpp.s

.PHONY : src/util/ArgumentParser.s

# target to generate assembly for a file
src/util/ArgumentParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/ArgumentParser.cpp.s
.PHONY : src/util/ArgumentParser.cpp.s

src/util/Logging.o: src/util/Logging.cpp.o

.PHONY : src/util/Logging.o

# target to build an object file
src/util/Logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/Logging.cpp.o
.PHONY : src/util/Logging.cpp.o

src/util/Logging.i: src/util/Logging.cpp.i

.PHONY : src/util/Logging.i

# target to preprocess a source file
src/util/Logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/Logging.cpp.i
.PHONY : src/util/Logging.cpp.i

src/util/Logging.s: src/util/Logging.cpp.s

.PHONY : src/util/Logging.s

# target to generate assembly for a file
src/util/Logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SecretBundestagServer.dir/build.make CMakeFiles/SecretBundestagServer.dir/src/util/Logging.cpp.s
.PHONY : src/util/Logging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... SecretBundestagServer"
	@echo "... WebSocketCppClientExample"
	@echo "... WebsocketCpp"
	@echo "... WebsocketCppServerExample"
	@echo "... src/comm/ConnectionHandler.o"
	@echo "... src/comm/ConnectionHandler.i"
	@echo "... src/comm/ConnectionHandler.s"
	@echo "... src/comm/Lobby.o"
	@echo "... src/comm/Lobby.i"
	@echo "... src/comm/Lobby.s"
	@echo "... src/comm/LobbyHandler.o"
	@echo "... src/comm/LobbyHandler.i"
	@echo "... src/comm/LobbyHandler.s"
	@echo "... src/gamelogic/gamecontroller/Controller.o"
	@echo "... src/gamelogic/gamecontroller/Controller.i"
	@echo "... src/gamelogic/gamecontroller/Controller.s"
	@echo "... src/gamelogic/gamemodel/Board.o"
	@echo "... src/gamelogic/gamemodel/Board.i"
	@echo "... src/gamelogic/gamemodel/Board.s"
	@echo "... src/gamelogic/gamemodel/CardRange.o"
	@echo "... src/gamelogic/gamemodel/CardRange.i"
	@echo "... src/gamelogic/gamemodel/CardRange.s"
	@echo "... src/gamelogic/gamemodel/Environment.o"
	@echo "... src/gamelogic/gamemodel/Environment.i"
	@echo "... src/gamelogic/gamemodel/Environment.s"
	@echo "... src/gamelogic/gamemodel/EventTrigger.o"
	@echo "... src/gamelogic/gamemodel/EventTrigger.i"
	@echo "... src/gamelogic/gamemodel/EventTrigger.s"
	@echo "... src/gamelogic/gamemodel/GameStateRepresentation.o"
	@echo "... src/gamelogic/gamemodel/GameStateRepresentation.i"
	@echo "... src/gamelogic/gamemodel/GameStateRepresentation.s"
	@echo "... src/gamelogic/gamemodel/Player.o"
	@echo "... src/gamelogic/gamemodel/Player.i"
	@echo "... src/gamelogic/gamemodel/Player.s"
	@echo "... src/gamelogic/gamemodel/RuleSet.o"
	@echo "... src/gamelogic/gamemodel/RuleSet.i"
	@echo "... src/gamelogic/gamemodel/RuleSet.s"
	@echo "... src/gamelogic/gamemodel/SingleCardEventTrigger.o"
	@echo "... src/gamelogic/gamemodel/SingleCardEventTrigger.i"
	@echo "... src/gamelogic/gamemodel/SingleCardEventTrigger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/messages/Accept.o"
	@echo "... src/messages/Accept.i"
	@echo "... src/messages/Accept.s"
	@echo "... src/messages/Error.o"
	@echo "... src/messages/Error.i"
	@echo "... src/messages/Error.s"
	@echo "... src/messages/GameStart.o"
	@echo "... src/messages/GameStart.i"
	@echo "... src/messages/GameStart.s"
	@echo "... src/messages/JoinRequest.o"
	@echo "... src/messages/JoinRequest.i"
	@echo "... src/messages/JoinRequest.s"
	@echo "... src/messages/Message.o"
	@echo "... src/messages/Message.i"
	@echo "... src/messages/Message.s"
	@echo "... src/messages/Player.o"
	@echo "... src/messages/Player.i"
	@echo "... src/messages/Player.s"
	@echo "... src/messages/StartRequest.o"
	@echo "... src/messages/StartRequest.i"
	@echo "... src/messages/StartRequest.s"
	@echo "... src/util/ArgumentParser.o"
	@echo "... src/util/ArgumentParser.i"
	@echo "... src/util/ArgumentParser.s"
	@echo "... src/util/Logging.o"
	@echo "... src/util/Logging.i"
	@echo "... src/util/Logging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

