//
// Created by bjorn on 08.12.20.
//

#ifndef SECRETBUNDESTAGSERVER_GAMESTATEREPRESENTATION_HPP
#define SECRETBUNDESTAGSERVER_GAMESTATEREPRESENTATION_HPP


class GameStateRepresentation {

};


#endif //SECRETBUNDESTAGSERVER_GAMESTATEREPRESENTATION_HPP
