name: Check
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install LWS
        run: |
          sudo apt install libssl-dev
          git clone https://github.com/warmcat/libwebsockets.git
          cd libwebsockets
          CC=gcc-10 CXX=g++-10 cmake .
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf libwebsockets
          sudo ldconfig
      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  ..
      - name: Run Clang Tidy
        run: |
          run-clang-tidy -j$(nproc) -quiet
      - name: Test
        run: |
          ./build/test/Tests
