name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      package_name: secretbundestagserver
      package_version: 1.0-1

    steps:
      - name: Checkout️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Setup .deb Directory
        run: |
          mkdir -p $package_name_$package_version/usr/local/bin
      - name: Install Lws
        run: |
          sudo apt install libssl-dev
          git clone https://github.com/warmcat/libwebsockets.git
          cd libwebsockets
          cmake .
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf libwebsockets
          sudo ldconfig
      - name: Build Application
        run: |
          mkdir build
          cd build
          make -j$(nproc)
          cp SecretBundestagServer $package_name_$package_version/usr/local/bin
      - name: Install LWS into Package
        run: |
          cd libwebsockets
          cmake -DCMAKE_INSTALL_DIRECTORY=$package_name_$package_version/usr/local
          make -j$(nproc)
          sudo make install
      - name: Install Package config
        run: |
          mkdir -p $package_name_$package_version/DEBIAN
          cp package/debian_control $package_name_$package_version/DEBIAN/control
          sed -i 's/PACKAGE_NAME/$package_name/g' $package_name_$package_version/DEBIAN/control
          sed -i 's/PACKAGE_VERSION/$package_version/g' $package_name_$package_version/DEBIAN/control
      - name: Build Package
        run: dpkg-deb --build $package_name_$package_version
      - name: Move Package into deploy dir
        run: |
          mkdir deploy
          cp *.deb deploy/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.MOBAR_BOT_DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          CLEAN: true
