name: Compile
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        cxx: [g++-8, g++-9, g++-10, clang++-9, clang++-10, clang++-11]
        build: [Release, Debug]
    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install LWS
        run: |
          sudo apt install libssl-dev
          git clone https://github.com/warmcat/libwebsockets.git
          cd libwebsockets
          cmake .
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf libwebsockets
          sudo ldconfig
      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
      - name: Build
        run: |
          cd build
          make -j$(nproc)
      - name: Test
        run: |
          ./build/test/Tests
