name: Compile
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        compilers: ["gcc-8 g++-8", "gcc-9 g++-9", "gcc-10 g++-10", "clang-9 clang++-9", "clang-10 clang++-10", "clang-11 clang++-11"]
        build: [Release, Debug]
    env:
      CC: ${{ ($matrix.compilers)[0] }}
      CXX: ${{ ($matrix.compilers)[1] }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install LWS
        run: |
          sudo apt install libssl-dev
          git clone https://github.com/warmcat/libwebsockets.git
          cd libwebsockets
          cmake .
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf libwebsockets
          sudo ldconfig
      - name: Install GTest
        run: |
          sudo apt install libgtest-dev google-mock
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make -j$(nproc)
          sudo cp *.a /usr/lib
          cd /usr/src/gmock
          sudo cmake CMakeLists.txt
          sudo make -j$(nproc)
          sudo cp *.a /usr/lib
      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
      - name: Build
        run: |
          cd build
          make -j$(nproc)
      - name: Test
        run: |
          ./build/test/Tests
